"""showbuilder/codegen.py -- Generate Python + VBA validators from showbuilder.db.

Reads the LIVE database produced by dump_wb.py and emits:
  - Python validate_row(table, row) function  →  validate_row.py
  - VBA ValidateRow() Sub per table           →  validators.bas

Usage:
    python showbuilder/codegen.py [--db PATH] [--out-dir PATH]

Defaults:
    --db     <workspace>/showbuilder.db
    --out-dir <workspace>/showbuilder   (alongside this script)

Both output files are overwritten on every run.  Re-run after schema changes
(add column / add enum value / add table) and after re-running dump_wb.py.

Source of truth: showbuilder/schema.sql.
Workflow note: see the signpost comment at the top of showbuilder/schema.py.
"""

import argparse
import os
import re
import sqlite3
import textwrap

_HERE = os.path.dirname(os.path.abspath(__file__))
_DEFAULT_DB  = os.path.join(os.path.dirname(_HERE), "showbuilder.db")
_DEFAULT_OUT = _HERE


# ---------------------------------------------------------------------------
# Schema introspection
# ---------------------------------------------------------------------------

def _table_names(con):
    rows = con.execute(
        "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
    ).fetchall()
    return [r[0] for r in rows]


def _column_info(con, table):
    """Return list of {name, type, notnull, pk} dicts."""
    rows = con.execute(f"PRAGMA table_info({table})").fetchall()
    return [
        {"name": r[1], "type": r[2], "notnull": bool(r[3]), "pk": bool(r[5])}
        for r in rows
    ]


def _fk_info(con, table):
    """Return list of {from_col, to_table, to_col} dicts."""
    rows = con.execute(f"PRAGMA foreign_key_list({table})").fetchall()
    seen = {}
    for r in rows:
        # id, seq, table, from, to, on_update, on_delete, match
        key = (r[3], r[2], r[4])  # from_col, to_table, to_col
        seen[key] = {"from_col": r[3], "to_table": r[2], "to_col": r[4]}
    return list(seen.values())


def _check_constraints(con, table):
    """Return list of CHECK constraint text strings extracted from DDL."""
    row = con.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (table,)
    ).fetchone()
    if not row or not row[0]:
        return []
    # Extract the contents of each CHECK(...) block.
    # Pattern allows one level of nested parens (needed for IN ('a','b') checks).
    return re.findall(r"CHECK\s*\(((?:[^()]*|\([^()]*\))*)\)", row[0], re.IGNORECASE)


def _parse_enum_check(check_text):
    """
    Given a CHECK body like "asset_type IN ('image', 'video', 'youtube')"
    return (column_name, [values]).  Returns None if pattern not recognised.
    Also handles optional NULL/empty-string variants, e.g.:
      CHECK (fit_mode IN ('cover','contain',NULL,''))
    """
    m = re.match(
        r"(\w+)\s+IN\s*\(([^)]+)\)",
        check_text.strip(),
        re.IGNORECASE,
    )
    if not m:
        return None
    col = m.group(1)
    raw_vals = m.group(2)
    values = []
    for tok in raw_vals.split(","):
        tok = tok.strip().strip("'\"")
        if tok.upper() == "NULL" or tok == "":
            continue
        values.append(tok)
    return (col, values) if values else None


def introspect(db_path):
    """
    Return a dict keyed by table name, each value being:
      {
        "columns":  [{name, type, notnull, pk}, ...],
        "fks":      [{from_col, to_table, to_col}, ...],
        "checks":   [(col_name, [enum_value, ...]), ...],   # parsed IN checks only
        "polymorphic_fk": bool,   # True for sequence_entries.target_id
      }
    """
    con = sqlite3.connect(db_path)
    schema = {}
    for table in _table_names(con):
        cols   = _column_info(con, table)
        fks    = _fk_info(con, table)
        checks = []
        for raw in _check_constraints(con, table):
            parsed = _parse_enum_check(raw)
            if parsed:
                checks.append(parsed)
        poly = table == "sequence_entries"
        schema[table] = {
            "columns":        cols,
            "fks":            fks,
            "checks":         checks,
            "polymorphic_fk": poly,
        }
    con.close()
    return schema


# ---------------------------------------------------------------------------
# Python emitter
# ---------------------------------------------------------------------------

_PY_HEADER = '''\
"""validate_row.py -- AUTO-GENERATED by showbuilder/codegen.py.  DO NOT EDIT.

Re-generate with:
    python showbuilder/codegen.py

Source of truth: showbuilder/schema.sql
"""
from __future__ import annotations


ENUM_VALUES: dict[str, dict[str, list[str]]] = {
'''

_PY_FOOTER = '''\

def validate_row(table: str, row: dict) -> list[str]:
    """Validate a data row against schema rules.

    Returns a (possibly empty) list of error messages.
    Missing/None values are allowed for nullable columns.
    """
    errors: list[str] = []
    table_checks = ENUM_VALUES.get(table, {})
    for col, allowed in table_checks.items():
        val = row.get(col)
        if val is None or val == "":
            continue
        if val not in allowed:
            errors.append(
                f"{table}.{col}: invalid value {val!r}; "
                f"allowed: {allowed}"
            )
    return errors
'''


def build_py(schema):
    lines = [_PY_HEADER]
    for table, info in sorted(schema.items()):
        if not info["checks"]:
            continue
        lines.append(f'    "{table}": {{')
        for col, values in info["checks"]:
            vals_repr = ", ".join(f'"{v}"' for v in values)
            lines.append(f'        "{col}": [{vals_repr}],')
        lines.append("    },")
    lines.append("}")
    lines.append(_PY_FOOTER)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# VBA emitter
# ---------------------------------------------------------------------------

_VBA_HEADER = """\
' validators.bas -- AUTO-GENERATED by showbuilder/codegen.py.  DO NOT EDIT.
' Re-generate: python showbuilder/codegen.py
' Source of truth: showbuilder/schema.sql
'
' Usage: inject into the workbook via excel_project.py / YTExcelDriver.initialise()
' Each sub validates a single data row and writes errors to the Errors column.
' Call from sheet event handlers or a ribbon "Validate" button.
Option Explicit

"""

def _vba_for_table(table, info):
    """Emit a VBA Sub that validates a row in the sheet for `table`."""
    if not info["checks"] and not info["polymorphic_fk"]:
        return ""

    lines = []
    sub_name = "Validate_" + table
    lines.append(f"Public Sub {sub_name}(ws As Worksheet, rowNum As Long)")
    lines.append(f"    ' Validates one data row in the '{table}' sheet.")
    lines.append( "    Dim errors As String")
    lines.append( '    errors = ""')
    lines.append( "")

    for col, values in info["checks"]:
        vba_vals = ", ".join(f'"{v}"' for v in values)
        lines.append(f"    ' {col} enum check")
        lines.append(f'    Dim val_{col} As String')
        # Assumes column header names map 1:1 to sheet column headers.
        # Caller must adapt column index lookup to their sheet layout.
        lines.append(
            f'    val_{col} = Trim(CStr(ws.Cells(rowNum, '
            f'ColIndex(ws, "{col}")).Value))'
        )
        lines.append(f'    If val_{col} <> "" Then')
        lines.append(f'        Select Case val_{col}')
        lines.append(f'        Case {vba_vals}')
        lines.append( '            ' + "' OK")
        lines.append( '        Case Else')
        lines.append(
            f'            errors = errors & "{col}: invalid value [" '
            f'& val_{col} & "] allowed: {values}" & vbLf'
        )
        lines.append( '        End Select')
        lines.append( '    End If')
        lines.append( "")

    if info["polymorphic_fk"]:
        lines.append("    ' Polymorphic FK: target_id must exist in items or sequences")
        lines.append("    ' depending on entry_type.  Implement via DB query or cache.")
        lines.append("    ' (special-case: not auto-verifiable via simple column check)")
        lines.append("")

    lines.append('    If errors <> "" Then')
    lines.append(
        f'        ws.Cells(rowNum, ColIndex(ws, "errors")).Value = errors'
    )
    lines.append("    End If")
    lines.append(f"End Sub")
    lines.append("")
    return "\n".join(lines)


def _vba_col_index_helper():
    """Emit a shared ColIndex() helper function."""
    return textwrap.dedent("""\
        ' ---------------------------------------------------------------------------
        ' Helper: return column index for a given header name in row 1.
        ' ---------------------------------------------------------------------------
        Private Function ColIndex(ws As Worksheet, headerName As String) As Long
            Dim c As Long
            For c = 1 To ws.UsedRange.Columns.Count
                If Trim(CStr(ws.Cells(1, c).Value)) = headerName Then
                    ColIndex = c
                    Exit Function
                End If
            Next c
            ColIndex = 0   ' not found
        End Function
        """)


def build_vba(schema):
    parts = [_VBA_HEADER, _vba_col_index_helper()]
    for table in sorted(schema.keys()):
        vba = _vba_for_table(table, schema[table])
        if vba:
            parts.append(vba)
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate validators from showbuilder.db")
    parser.add_argument("--db",      default=_DEFAULT_DB,  help="Path to showbuilder.db")
    parser.add_argument("--out-dir", default=_DEFAULT_OUT, help="Output directory")
    args = parser.parse_args()

    if not os.path.exists(args.db):
        raise FileNotFoundError(
            f"Database not found: {args.db}\n"
            "Run dump_wb.py first to create it."
        )

    print(f"Introspecting {args.db} ...")
    schema = introspect(args.db)
    print(f"  tables: {', '.join(sorted(schema.keys()))}")

    py_path  = os.path.join(args.out_dir, "validate_row.py")
    vba_path = os.path.join(args.out_dir, "validators.bas")

    py_src  = build_py(schema)
    vba_src = build_vba(schema)

    with open(py_path,  "w", encoding="utf-8") as f:
        f.write(py_src)
    print(f"  wrote {py_path}")

    with open(vba_path, "w", encoding="utf-8") as f:
        f.write(vba_src)
    print(f"  wrote {vba_path}")


if __name__ == "__main__":
    main()
