"""validate_row.py -- AUTO-GENERATED by showbuilder/codegen.py.  DO NOT EDIT.

Re-generate with:
    python showbuilder/codegen.py

Source of truth: showbuilder/schema.sql
"""
from __future__ import annotations


ENUM_VALUES: dict[str, dict[str, list[str]]] = {

    "assets": {
        "asset_type": ["image", "video", "youtube"],
        "enabled": ["0", "1"],
    },
    "formats": {
        "enabled": ["0", "1"],
    },
    "icloud_accounts": {
        "enabled": ["0", "1"],
    },
    "icloud_photos": {
        "media_type": ["image", "video"],
    },
    "items": {
        "duration_mode": ["fixed", "to_media_end"],
        "track_kind": ["video_main", "video_overlay", "text_overlay"],
        "media_audio_mode": ["mute", "normal", "ducked"],
        "fit_mode": ["cover", "contain", "stretch", "none"],
        "enabled": ["0", "1"],
    },
    "regions": {
        "anchor": ["top_left", "top_center", "top_right", "center_left", "center", "center_right", "bottom_left", "bottom_center", "bottom_right"],
        "enabled": ["0", "1"],
    },
    "sequence_entries": {
        "entry_type": ["item", "sequence"],
        "track_kind": ["video_main", "video_overlay", "text_overlay"],
        "enabled": ["0", "1"],
    },
    "sequences": {
        "sequence_type": ["show", "block", "playlist"],
        "timing_mode": ["serial", "parallel"],
        "enabled": ["0", "1"],
    },
    "styles": {
        "enabled": ["0", "1"],
    },
    "text_overlays": {
        "position_mode": ["preset", "coords"],
        "position_preset": ["top_left", "top_center", "top_right", "center_left", "center", "center_right", "bottom_left", "bottom_center", "bottom_right"],
        "anchor": ["top_left", "top_center", "top_right", "center_left", "center", "center_right", "bottom_left", "bottom_center", "bottom_right"],
        "align": ["left", "center", "right"],
        "enabled": ["0", "1"],
    },
    "text_sets": {
        "enabled": ["0", "1"],
    },
}

def validate_row(table: str, row: dict) -> list[str]:
    """Validate a data row against schema rules.

    Returns a (possibly empty) list of error messages.
    Missing/None values are allowed for nullable columns.
    """
    errors: list[str] = []
    table_checks = ENUM_VALUES.get(table, {})
    for col, allowed in table_checks.items():
        val = row.get(col)
        if val is None or val == "":
            continue
        if val not in allowed:
            errors.append(
                f"{table}.{col}: invalid value {val!r}; "
                f"allowed: {allowed}"
            )
    return errors
