' validators.bas -- AUTO-GENERATED by showbuilder/codegen.py.  DO NOT EDIT.
' Re-generate: python showbuilder/codegen.py
' Source of truth: showbuilder/schema.sql
'
' Usage: inject into the workbook via excel_project.py / YTExcelDriver.initialise()
' Each sub validates a single data row and writes errors to the Errors column.
' Call from sheet event handlers or a ribbon "Validate" button.
Option Explicit


' ---------------------------------------------------------------------------
' Helper: return column index for a given header name in row 1.
' ---------------------------------------------------------------------------
Private Function ColIndex(ws As Worksheet, headerName As String) As Long
    Dim c As Long
    For c = 1 To ws.UsedRange.Columns.Count
        If Trim(CStr(ws.Cells(1, c).Value)) = headerName Then
            ColIndex = c
            Exit Function
        End If
    Next c
    ColIndex = 0   ' not found
End Function

Public Sub Validate_assets(ws As Worksheet, rowNum As Long)
    ' Validates one data row in the 'assets' sheet.
    Dim errors As String
    errors = ""

    ' asset_type enum check
    Dim val_asset_type As String
    val_asset_type = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "asset_type")).Value))
    If val_asset_type <> "" Then
        Select Case val_asset_type
        Case "image", "video", "youtube"
            ' OK
        Case Else
            errors = errors & "asset_type: invalid value [" & val_asset_type & "] allowed: ['image', 'video', 'youtube']" & vbLf
        End Select
    End If

    ' enabled enum check
    Dim val_enabled As String
    val_enabled = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "enabled")).Value))
    If val_enabled <> "" Then
        Select Case val_enabled
        Case "0", "1"
            ' OK
        Case Else
            errors = errors & "enabled: invalid value [" & val_enabled & "] allowed: ['0', '1']" & vbLf
        End Select
    End If

    If errors <> "" Then
        ws.Cells(rowNum, ColIndex(ws, "errors")).Value = errors
    End If
End Sub

Public Sub Validate_formats(ws As Worksheet, rowNum As Long)
    ' Validates one data row in the 'formats' sheet.
    Dim errors As String
    errors = ""

    ' enabled enum check
    Dim val_enabled As String
    val_enabled = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "enabled")).Value))
    If val_enabled <> "" Then
        Select Case val_enabled
        Case "0", "1"
            ' OK
        Case Else
            errors = errors & "enabled: invalid value [" & val_enabled & "] allowed: ['0', '1']" & vbLf
        End Select
    End If

    If errors <> "" Then
        ws.Cells(rowNum, ColIndex(ws, "errors")).Value = errors
    End If
End Sub

Public Sub Validate_icloud_accounts(ws As Worksheet, rowNum As Long)
    ' Validates one data row in the 'icloud_accounts' sheet.
    Dim errors As String
    errors = ""

    ' enabled enum check
    Dim val_enabled As String
    val_enabled = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "enabled")).Value))
    If val_enabled <> "" Then
        Select Case val_enabled
        Case "0", "1"
            ' OK
        Case Else
            errors = errors & "enabled: invalid value [" & val_enabled & "] allowed: ['0', '1']" & vbLf
        End Select
    End If

    If errors <> "" Then
        ws.Cells(rowNum, ColIndex(ws, "errors")).Value = errors
    End If
End Sub

Public Sub Validate_icloud_photos(ws As Worksheet, rowNum As Long)
    ' Validates one data row in the 'icloud_photos' sheet.
    Dim errors As String
    errors = ""

    ' media_type enum check
    Dim val_media_type As String
    val_media_type = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "media_type")).Value))
    If val_media_type <> "" Then
        Select Case val_media_type
        Case "image", "video"
            ' OK
        Case Else
            errors = errors & "media_type: invalid value [" & val_media_type & "] allowed: ['image', 'video']" & vbLf
        End Select
    End If

    If errors <> "" Then
        ws.Cells(rowNum, ColIndex(ws, "errors")).Value = errors
    End If
End Sub

Public Sub Validate_items(ws As Worksheet, rowNum As Long)
    ' Validates one data row in the 'items' sheet.
    Dim errors As String
    errors = ""

    ' duration_mode enum check
    Dim val_duration_mode As String
    val_duration_mode = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "duration_mode")).Value))
    If val_duration_mode <> "" Then
        Select Case val_duration_mode
        Case "fixed", "to_media_end"
            ' OK
        Case Else
            errors = errors & "duration_mode: invalid value [" & val_duration_mode & "] allowed: ['fixed', 'to_media_end']" & vbLf
        End Select
    End If

    ' track_kind enum check
    Dim val_track_kind As String
    val_track_kind = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "track_kind")).Value))
    If val_track_kind <> "" Then
        Select Case val_track_kind
        Case "video_main", "video_overlay", "text_overlay"
            ' OK
        Case Else
            errors = errors & "track_kind: invalid value [" & val_track_kind & "] allowed: ['video_main', 'video_overlay', 'text_overlay']" & vbLf
        End Select
    End If

    ' media_audio_mode enum check
    Dim val_media_audio_mode As String
    val_media_audio_mode = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "media_audio_mode")).Value))
    If val_media_audio_mode <> "" Then
        Select Case val_media_audio_mode
        Case "mute", "normal", "ducked"
            ' OK
        Case Else
            errors = errors & "media_audio_mode: invalid value [" & val_media_audio_mode & "] allowed: ['mute', 'normal', 'ducked']" & vbLf
        End Select
    End If

    ' fit_mode enum check
    Dim val_fit_mode As String
    val_fit_mode = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "fit_mode")).Value))
    If val_fit_mode <> "" Then
        Select Case val_fit_mode
        Case "cover", "contain", "stretch", "none"
            ' OK
        Case Else
            errors = errors & "fit_mode: invalid value [" & val_fit_mode & "] allowed: ['cover', 'contain', 'stretch', 'none']" & vbLf
        End Select
    End If

    ' enabled enum check
    Dim val_enabled As String
    val_enabled = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "enabled")).Value))
    If val_enabled <> "" Then
        Select Case val_enabled
        Case "0", "1"
            ' OK
        Case Else
            errors = errors & "enabled: invalid value [" & val_enabled & "] allowed: ['0', '1']" & vbLf
        End Select
    End If

    If errors <> "" Then
        ws.Cells(rowNum, ColIndex(ws, "errors")).Value = errors
    End If
End Sub

Public Sub Validate_regions(ws As Worksheet, rowNum As Long)
    ' Validates one data row in the 'regions' sheet.
    Dim errors As String
    errors = ""

    ' anchor enum check
    Dim val_anchor As String
    val_anchor = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "anchor")).Value))
    If val_anchor <> "" Then
        Select Case val_anchor
        Case "top_left", "top_center", "top_right", "center_left", "center", "center_right", "bottom_left", "bottom_center", "bottom_right"
            ' OK
        Case Else
            errors = errors & "anchor: invalid value [" & val_anchor & "] allowed: ['top_left', 'top_center', 'top_right', 'center_left', 'center', 'center_right', 'bottom_left', 'bottom_center', 'bottom_right']" & vbLf
        End Select
    End If

    ' enabled enum check
    Dim val_enabled As String
    val_enabled = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "enabled")).Value))
    If val_enabled <> "" Then
        Select Case val_enabled
        Case "0", "1"
            ' OK
        Case Else
            errors = errors & "enabled: invalid value [" & val_enabled & "] allowed: ['0', '1']" & vbLf
        End Select
    End If

    If errors <> "" Then
        ws.Cells(rowNum, ColIndex(ws, "errors")).Value = errors
    End If
End Sub

Public Sub Validate_sequence_entries(ws As Worksheet, rowNum As Long)
    ' Validates one data row in the 'sequence_entries' sheet.
    Dim errors As String
    errors = ""

    ' entry_type enum check
    Dim val_entry_type As String
    val_entry_type = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "entry_type")).Value))
    If val_entry_type <> "" Then
        Select Case val_entry_type
        Case "item", "sequence"
            ' OK
        Case Else
            errors = errors & "entry_type: invalid value [" & val_entry_type & "] allowed: ['item', 'sequence']" & vbLf
        End Select
    End If

    ' track_kind enum check
    Dim val_track_kind As String
    val_track_kind = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "track_kind")).Value))
    If val_track_kind <> "" Then
        Select Case val_track_kind
        Case "video_main", "video_overlay", "text_overlay"
            ' OK
        Case Else
            errors = errors & "track_kind: invalid value [" & val_track_kind & "] allowed: ['video_main', 'video_overlay', 'text_overlay']" & vbLf
        End Select
    End If

    ' enabled enum check
    Dim val_enabled As String
    val_enabled = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "enabled")).Value))
    If val_enabled <> "" Then
        Select Case val_enabled
        Case "0", "1"
            ' OK
        Case Else
            errors = errors & "enabled: invalid value [" & val_enabled & "] allowed: ['0', '1']" & vbLf
        End Select
    End If

    ' Polymorphic FK: target_id must exist in items or sequences
    ' depending on entry_type.  Implement via DB query or cache.
    ' (special-case: not auto-verifiable via simple column check)

    If errors <> "" Then
        ws.Cells(rowNum, ColIndex(ws, "errors")).Value = errors
    End If
End Sub

Public Sub Validate_sequences(ws As Worksheet, rowNum As Long)
    ' Validates one data row in the 'sequences' sheet.
    Dim errors As String
    errors = ""

    ' sequence_type enum check
    Dim val_sequence_type As String
    val_sequence_type = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "sequence_type")).Value))
    If val_sequence_type <> "" Then
        Select Case val_sequence_type
        Case "show", "block", "playlist"
            ' OK
        Case Else
            errors = errors & "sequence_type: invalid value [" & val_sequence_type & "] allowed: ['show', 'block', 'playlist']" & vbLf
        End Select
    End If

    ' timing_mode enum check
    Dim val_timing_mode As String
    val_timing_mode = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "timing_mode")).Value))
    If val_timing_mode <> "" Then
        Select Case val_timing_mode
        Case "serial", "parallel"
            ' OK
        Case Else
            errors = errors & "timing_mode: invalid value [" & val_timing_mode & "] allowed: ['serial', 'parallel']" & vbLf
        End Select
    End If

    ' enabled enum check
    Dim val_enabled As String
    val_enabled = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "enabled")).Value))
    If val_enabled <> "" Then
        Select Case val_enabled
        Case "0", "1"
            ' OK
        Case Else
            errors = errors & "enabled: invalid value [" & val_enabled & "] allowed: ['0', '1']" & vbLf
        End Select
    End If

    If errors <> "" Then
        ws.Cells(rowNum, ColIndex(ws, "errors")).Value = errors
    End If
End Sub

Public Sub Validate_styles(ws As Worksheet, rowNum As Long)
    ' Validates one data row in the 'styles' sheet.
    Dim errors As String
    errors = ""

    ' enabled enum check
    Dim val_enabled As String
    val_enabled = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "enabled")).Value))
    If val_enabled <> "" Then
        Select Case val_enabled
        Case "0", "1"
            ' OK
        Case Else
            errors = errors & "enabled: invalid value [" & val_enabled & "] allowed: ['0', '1']" & vbLf
        End Select
    End If

    If errors <> "" Then
        ws.Cells(rowNum, ColIndex(ws, "errors")).Value = errors
    End If
End Sub

Public Sub Validate_text_overlays(ws As Worksheet, rowNum As Long)
    ' Validates one data row in the 'text_overlays' sheet.
    Dim errors As String
    errors = ""

    ' position_mode enum check
    Dim val_position_mode As String
    val_position_mode = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "position_mode")).Value))
    If val_position_mode <> "" Then
        Select Case val_position_mode
        Case "preset", "coords"
            ' OK
        Case Else
            errors = errors & "position_mode: invalid value [" & val_position_mode & "] allowed: ['preset', 'coords']" & vbLf
        End Select
    End If

    ' position_preset enum check
    Dim val_position_preset As String
    val_position_preset = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "position_preset")).Value))
    If val_position_preset <> "" Then
        Select Case val_position_preset
        Case "top_left", "top_center", "top_right", "center_left", "center", "center_right", "bottom_left", "bottom_center", "bottom_right"
            ' OK
        Case Else
            errors = errors & "position_preset: invalid value [" & val_position_preset & "] allowed: ['top_left', 'top_center', 'top_right', 'center_left', 'center', 'center_right', 'bottom_left', 'bottom_center', 'bottom_right']" & vbLf
        End Select
    End If

    ' anchor enum check
    Dim val_anchor As String
    val_anchor = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "anchor")).Value))
    If val_anchor <> "" Then
        Select Case val_anchor
        Case "top_left", "top_center", "top_right", "center_left", "center", "center_right", "bottom_left", "bottom_center", "bottom_right"
            ' OK
        Case Else
            errors = errors & "anchor: invalid value [" & val_anchor & "] allowed: ['top_left', 'top_center', 'top_right', 'center_left', 'center', 'center_right', 'bottom_left', 'bottom_center', 'bottom_right']" & vbLf
        End Select
    End If

    ' align enum check
    Dim val_align As String
    val_align = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "align")).Value))
    If val_align <> "" Then
        Select Case val_align
        Case "left", "center", "right"
            ' OK
        Case Else
            errors = errors & "align: invalid value [" & val_align & "] allowed: ['left', 'center', 'right']" & vbLf
        End Select
    End If

    ' enabled enum check
    Dim val_enabled As String
    val_enabled = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "enabled")).Value))
    If val_enabled <> "" Then
        Select Case val_enabled
        Case "0", "1"
            ' OK
        Case Else
            errors = errors & "enabled: invalid value [" & val_enabled & "] allowed: ['0', '1']" & vbLf
        End Select
    End If

    If errors <> "" Then
        ws.Cells(rowNum, ColIndex(ws, "errors")).Value = errors
    End If
End Sub

Public Sub Validate_text_sets(ws As Worksheet, rowNum As Long)
    ' Validates one data row in the 'text_sets' sheet.
    Dim errors As String
    errors = ""

    ' enabled enum check
    Dim val_enabled As String
    val_enabled = Trim(CStr(ws.Cells(rowNum, ColIndex(ws, "enabled")).Value))
    If val_enabled <> "" Then
        Select Case val_enabled
        Case "0", "1"
            ' OK
        Case Else
            errors = errors & "enabled: invalid value [" & val_enabled & "] allowed: ['0', '1']" & vbLf
        End Select
    End If

    If errors <> "" Then
        ws.Cells(rowNum, ColIndex(ws, "errors")).Value = errors
    End If
End Sub
